---
- name: Create Cloudera Director instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ lookup('ini', 'key_name section=director file=cloudera.ini') }}"
         group_id: "{{ lookup('ini', 'security_group section=director file=cloudera.ini') }}"
         instance_type: "{{ lookup('ini', 'instance_type section=director  file=cloudera.ini') }}"
         image: "{{ lookup('ini', 'image section=director file=cloudera.ini') }}"
         wait: true
         wait_timeout: 600
         region: "{{ lookup('ini', 'region  section=director file=cloudera.ini') }}"
         vpc_subnet_id: "{{ lookup('ini', 'vpc_subnet_id  section=director file=cloudera.ini') }}"
         assign_public_ip: false
         instance_profile_name: "{{ lookup('ini', 'instance_profile_name  section=director file=cloudera.ini') }}"
         exact_count: "{{ lookup('ini', 'instance_count  section=director file=cloudera.ini') }}"
         count_tag:
           Name: "Director_{{ lookup('ini', 'instance_count  section=director file=cloudera.ini') }}"
         instance_tags:
           Name: "Cloudera Director"
      register: ec2_hosts
      
    - name: Set default on EC2 Instance
      set_fact:
        ec2_host_instance: "{{ ec2_hosts.tagged_instances[0] }}"
    - name: Set default facts on EC2 Instance
      set_fact:
        ec2_host_instance_ip: "{{ ec2_host_instance.private_ip }}"
        ec2_host_instance_id: "{{ ec2_host_instance.id }}"
    - name: Add new instance to host group
      add_host:
        hostname: "{{ ec2_host_instance_ip }}"
        groupname: director1
  
