---
- name: Create Cloudera Director instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch instance for cloudera director
      ec2:
         key_name: "{{ lookup('ini', 'key_name section=director file=cloudera.ini') }}"
         group_id: "{{ lookup('ini', 'security_group section=director file=cloudera.ini') }}"
         instance_type: "{{ lookup('ini', 'instance_type section=director  file=cloudera.ini') }}"
         image: "{{ lookup('ini', 'image section=director file=cloudera.ini') }}"
         wait: true
         wait_timeout: 600
         region: "{{ lookup('ini', 'region  section=director file=cloudera.ini') }}"
         vpc_subnet_id: "{{ lookup('ini', 'vpc_subnet_id  section=director file=cloudera.ini') }}"
         assign_public_ip: false
         instance_profile_name: "{{ lookup('ini', 'instance_profile_name  section=director file=cloudera.ini') }}"
         exact_count: "{{ lookup('ini', 'instance_count  section=director file=cloudera.ini') }}"
         count_tag:
           Name: "Director_{{ lookup('ini', 'instance_count  section=director file=cloudera.ini') }}"
         instance_tags:
           Name: "Cloudera Director"
      register: ec2_hosts
      
    - name: Set default on EC2 Instance
      set_fact:
        ec2_host_instance: "{{ ec2_hosts.tagged_instances[0] }}"
    - name: Set default facts on EC2 Instance
      set_fact:
        ec2_host_instance_ip: "{{ ec2_host_instance.private_ip }}"
        ec2_host_instance_id: "{{ ec2_host_instance.id }}"
    - name: Add new instance to host group
      add_host:
        hostname: "{{ ec2_host_instance_ip }}"
        groupname: director1
  
- name: Cloudera Director pre configurations setup
  hosts: director1
  remote_user: ec2_user
  become: yes
  become_method: sudo
  gather_facts: no 
  tasks:
    - name: Download Oracle JDK 
      shell: wget
      
    - name: Install Oracle JDK
      shell: yum localinstall -y --nogpgcheck /tmp/oraclejdk.rpm
    
    - name: Install MariaDB/Mysql
      shell: yum install -y mariadb
    
    - name: Download Cloudera Director Repo
      shell: http://archive.cloudera.com/director/redhat/7/x86_64/director/cloudera-director.repo
    
    - name : Install cloudera  director server
      shell: yum updates -y
      shell: yum install cloudera-director-server -y
    
    - name : Install cloudera director client      
      shell: yum install cloudera-director-client -y
      
    - name : start director server
      shell: sh ../bin/util/start-director.sh
    
    - name : Copy bootstrap file
      copy : 
        src: "bootstrap-scripts.sh" 
        dest: "/tmp/" 
        mode: "0775"
  - name: deploy_alluxio-env.sh
      template: 
        src: spark-hbase.conf.j2
        dest: "/tmp/spark-hbase.conf.j2"
  
  - name : bootstrap CDH5.12 cluster
      shell: rm -rf ../template/.*.conf.h2.db
      shell: cloudera-director bootstrap ../template/#[[TEMPLATE]].conf
        
